pytest install commands added

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -14,7 +14,8 @@ jobs:
     - name: Install dependencies
       run: |
         pip install --index-url https://rospypi.github.io/simple/ actionlib || echo "Skipping actionlib pip installation"
-        pip install -r api/requirements.txt || echo "Skipping missing dependencies"   
+        pip install -r api/requirements.txt || echo "Skipping missing dependencies"  
+        pip install pytest pytest-cov 
     - name: Run tests and collect coverage
       run: pytest --cov=api.calculator --cov-report=xml
     - name: Upload coverage reports to Codecov with GitHub Action
